export const cards = [
  { icon: "🐶", name: "Dog", set: "Animals" },
  { icon: "🐷", name: "Pig", set: "Animals" },
  { icon: "🦊", name: "Fox", set: "Animals" },
  { icon: "🐭", name: "Mouse", set: "Animals" },
  { icon: "🐱", name: "Cat", set: "Animals" },
  { icon: "🐮", name: "Cow", set: "Animals" },
  { icon: "🐻", name: "Bear", set: "Animals" },
  { icon: "🐨", name: "Koala", set: "Animals" },
  { icon: "🐸", name: "Frog", set: "Animals" },
  { icon: "🐴", name: "Horse", set: "Animals" },
  { icon: "🦁", name: "Lion", set: "Animals" },
  { icon: "🐧", name: "Penguin", set: "Animals" },
  { icon: "🐯", name: "Tiger", set: "Animals" },
  { icon: "🐙", name: "Octopus", set: "Animals" },
  { icon: "🦖", name: "T-Rex", set: "Animals" },
  { icon: "🐟", name: "Fish", set: "Animals" },
  { icon: "🦆", name: "Duck", set: "Animals" },
  { icon: "🐢", name: "Turtle", set: "Animals" },
  { icon: "🕷", name: "Spider", set: "Animals" },
  { icon: "🦙", name: "Llama", set: "Animals" },
  { icon: "🦏", name: "Rhino", set: "Animals" },
  { icon: "🦥", name: "Sloth", set: "Animals" },
  { icon: "🦨", name: "Skunk", set: "Animals" },
  { icon: "🐤", name: "Chick", set: "Animals" },
  { icon: "🐘", name: "Elephant", set: "Animals" },
  { icon: "🦦", name: "Otter", set: "Animals" },
  { icon: "🐳", name: "Whale", set: "Animals" },
  { icon: "🦉", name: "Owl", set: "Animals" },
  { icon: "🐜", name: "Ant", set: "Animals" },
  { icon: "🦛", name: "Hippo", set: "Animals" },
  { icon: "🦇", name: "Bat", set: "Animals" },
  { icon: "🐏", name: "Ram", set: "Animals" },
  { icon: "🐊", name: "Crocodile", set: "Animals" },
  { icon: "🦓", name: "Zebra", set: "Animals" },
  { icon: "🦈", name: "Shark", set: "Animals" },
  { icon: "🦗", name: "Grasshopper", set: "Animals" },
  { icon: "🦘", name: "Kangaroo", set: "Animals" },
  { icon: "🐫", name: "Camel", set: "Animals" },
  { icon: "𝟭", name: "One", set: "Numbers" },
  { icon: "𝟮", name: "Two", set: "Numbers" },
  { icon: "𝟯", name: "Three", set: "Numbers" },
  { icon: "𝟰", name: "Four", set: "Numbers" },
  { icon: "𝟱", name: "Five", set: "Numbers" },
  { icon: "𝟲", name: "Six", set: "Numbers" },
  { icon: "𝟳", name: "Seven", set: "Numbers" },
  { icon: "𝟴", name: "Eight", set: "Numbers" },
  { icon: "𝟵", name: "Nine", set: "Numbers" },
  { icon: "𝟭𝟢", name: "Ten", set: "Numbers" },
  { icon: "🚗", name: "Car", set: "Trucks" },
  { icon: "🚕", name: "Taxi", set: "Trucks" },
  { icon: "🚙", name: "Mini Van", set: "Trucks" },
  { icon: "🚌", name: "Bus", set: "Trucks" },
  { icon: "🚎", name: "Trolley", set: "Trucks" },
  { icon: "🏎", name: "Racecar", set: "Trucks" },
  { icon: "🚓", name: "Police Car", set: "Trucks" },
  { icon: "🚑", name: "Ambulance", set: "Trucks" },
  { icon: "🚒", name: "Fire Truck", set: "Trucks" },
  { icon: "🚐", name: "Van", set: "Trucks" },
  { icon: "🛻", name: "Truck", set: "Trucks" },
  { icon: "🚚", name: "Flat Bed Truck", set: "Trucks" },
  { icon: "🚛", name: "Semi Truck", set: "Trucks" },
  { icon: "🚜", name: "Tractor", set: "Trucks" },
  { icon: "🚲", name: "Bike", set: "Trucks" },
  { icon: "🚂", name: "Train", set: "Trucks" },
  { icon: "🚁", name: "Helicopter", set: "Trucks" },
  { icon: "🛸", name: "U F O", set: "Trucks" },
  { icon: "🚀", name: "Rocket", set: "Trucks" },
  { icon: "🚤", name: "Boat", set: "Trucks" },
  { icon: "🍌", name: "Banana", set: "Food" },
  { icon: "🧀", name: "Cheese", set: "Food" },
  { icon: "🥦", name: "Broccoli", set: "Food" },
  { icon: "🥚", name: "Egg", set: "Food" },
  { icon: "🥥", name: "Coconut", set: "Food" },
  { icon: "🍅", name: "Tomato", set: "Food" },
  { icon: "🍕", name: "Pizza", set: "Food" },
  { icon: "🍓", name: "Strawberry", set: "Food" },
  { icon: "🍑", name: "Peach", set: "Food" },
  { icon: "🍉", name: "Watermelon", set: "Food" },
  { icon: "🥕", name: "Carrot", set: "Food" },
  { icon: "🍏", name: "Apple", set: "Food" },
  { icon: "🍐", name: "Pear", set: "Food" },
  { icon: "🫐", name: "Blueberry", set: "Food" },
  { icon: "🫒", name: "Olive", set: "Food" },
];
